# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
  - container: battleship
    image: proscrumdev/battleship-cpp

pool:
  vmImage: 'Ubuntu-latest'

container: battleship

steps: 
- script: 'mkdir ./build'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Create build directory'

- script: 'cmake -S . -B ./build'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Configure using cmake'

- script: 'cmake --build ./build'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Build using cmake'
 
- script: 'ctest --output-junit $(Build.SourcesDirectory)/build/test_results.xml'
  workingDirectory: '$(Build.SourcesDirectory)/build'
  displayName: 'Execute Unit-Tests'
  
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Build.SourcesDirectory)/build/test_results.xml'
    testRunTitle: 'Google Test Results'
    mergeTestResults: true
    publishRunAttachments: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build/'
    Contents: 'Battleship'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'